change the module name in the import statements from `mymoodai_client` to `mymoodai`
The following import statement throws an error:
```python
from mymoodai_client import MyMoodAIClient
```

### Error:
---------------------------------------------------------------------------
```python
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[2], line 1
----> 1 from mymoodai_client import MyMoodAIClient

ModuleNotFoundError: No module named 'mymoodai_client'
```

This error occurs because `mymoodai_client` is not the correct module name. 
The correct module name is `mymoodai`. 

The import statement should be:

```python
from mymoodai import MyMoodAIClient
```