change the module from `mymoodai_client` to `mymoodai`
```python
from mymoodai_client import MyMoodAIClient
```
throws the error:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[2], line 1
----> 1 from mymoodai_client import MyMoodAIClient

ModuleNotFoundError: No module named 'mymoodai_client'
```

because mymoodai_client is not the correct module name but `mymoodai`.